// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       string `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Exchange string `json:"exchange"`
	SectorID string `json:"sectorId"`
}

type CompanySearchParams struct {
	Exchange  *string   `json:"exchange"`
	SectorIds []*string `json:"sectorIds"`
}

type Sector struct {
	ID           string  `json:"id"`
	Label        string  `json:"label"`
	LabelEnglish *string `json:"label_english"`
	Exchange     string  `json:"exchange"`
}

type Trade struct {
	Code       string `json:"code"`
	ClosePrice int    `json:"closePrice" bson:"close_price"`
	Volume     int    `json:"volume"`
	Timestamp  int    `json:"timestamp"`
}
